(()=>{
const $=x=>document.getElementById(x),map=L.map('map').setView([19.4326,-99.1332],11);L.control.scale({imperial:false}).addTo(map);
const bases={osm:L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{crossOrigin:true,attribution:'© OpenStreetMap'}),sat:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{crossOrigin:true,attribution:'© Esri'}),carto:L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{crossOrigin:true,attribution:'© CARTO'})};
let current=bases.osm.addTo(map),data=[],over2Data=[],over3Data=[],i=0,layers={},showB=true,showL=true,mode='individual',destinationGroups=[];
const icon=(c,t)=>L.divIcon({className:'',html:`<div class='pin ${c}'><b>${t}</b></div>`,iconSize:[26,26],iconAnchor:[13,26]});
const spiderIcon=(type,label)=>L.divIcon({className:'',html:`<div class='${type==='dest'?'spider-school-marker':'spider-origin-marker'}'>${label}</div>`,iconSize:type==='dest'?[34,34]:[22,22],iconAnchor:type==='dest'?[17,17]:[11,11]});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const hav=(a,b)=>{const R=6371,r=x=>x*Math.PI/180,d1=r(b.lat-a.lat),d2=r(b.lng-a.lng),q=Math.sin(d1/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
const fmt=k=>k<1?Math.round(k*1000)+' m':k.toFixed(2)+' km';
function distanceOf(r){return hav(L.latLng(r.lat_procedencia,r.lon_procedencia),L.latLng(r.lat_destino,r.lon_destino))}
function clear(){Object.values(layers).forEach(x=>{if(Array.isArray(x))x.forEach(y=>y&&map.hasLayer(y)&&map.removeLayer(y));else if(x&&map.hasLayer(x))map.removeLayer(x)});layers={}}
function cls(k){return k<=2?['Dentro de 2 km','inside']:k<=3?['Entre 2 y 3 km','middle']:['Mayor de 3 km','outside']}
function field(k,v){return `<div class='row'><span>${k}</span><span>${esc(v||'No disponible')}</span></div>`}
function popup(r,p){const pre=p==='Procedencia';return `<b>${esc(pre?r.nombre_procedencia:r.nombre_destino)}</b><br>CCT: ${esc(pre?r.cct_procedencia:r.cct_destino)}<br>Tipo: ${p}<br>Coordenadas: ${(pre?r.lat_procedencia:r.lat_destino).toFixed(6)}, ${(pre?r.lon_procedencia:r.lon_destino).toFixed(6)}<br>Alcaldía: ${esc(pre?r.alcaldia_procedencia:r.alcaldia_destino)}`}
function render(n){if(n<0||n>=data.length)return;mode='individual';setModeButtons();i=n;clear();let r=data[i],p=L.latLng(r.lat_procedencia,r.lon_procedencia),d=L.latLng(r.lat_destino,r.lon_destino),km=hav(p,d),c=cls(km);layers.b3=L.circle(p,{radius:3000,color:'#ef8a17',fillOpacity:.06,dashArray:'8 6'});layers.b2=L.circle(p,{radius:2000,color:'#1e9b55',fillOpacity:.08});layers.line=L.polyline([p,d],{color:'#59636f',weight:3,dashArray:'8 6'});layers.mp=L.marker(p,{icon:icon('blue','P')}).bindPopup(popup(r,'Procedencia'));layers.md=L.marker(d,{icon:icon('red','1')}).bindPopup(popup(r,'Primera opción'));layers.lab=L.marker([(p.lat+d.lat)/2,(p.lng+d.lng)/2],{interactive:false,icon:L.divIcon({className:'distance-label',html:fmt(km)})});if(showB){layers.b3.addTo(map);layers.b2.addTo(map)}if(showL){layers.line.addTo(map);layers.lab.addTo(map)}layers.mp.addTo(map);layers.md.addTo(map);map.fitBounds(L.featureGroup([layers.b3,layers.b2,layers.mp,layers.md]).getBounds().pad(.08));$('class').textContent=c[0];$('dist').textContent=fmt(km);$('result').className='result '+c[1];$('count').textContent=`Alumno ${i+1} de ${data.length}`;$('info').innerHTML=field('ID',r.id)+field('Nombre del alumno','No disponible en la base')+field('CCT procedencia',r.cct_procedencia)+field('Nombre procedencia',r.nombre_procedencia)+field('Alcaldía procedencia',r.alcaldia_procedencia)+field('CCT destino',r.cct_destino)+field('Nombre destino',r.nombre_destino)+field('Alcaldía destino',r.alcaldia_destino)+field('Nivel educativo',r.nivel_educativo)+field('Distancia Haversine',fmt(km))+field('Clasificación',c[0])+field('Cambio de alcaldía',r.alcaldia_procedencia&&r.alcaldia_destino?(r.alcaldia_procedencia===r.alcaldia_destino?'No':'Sí'):'No disponible');let u=new URL(location);u.searchParams.set('id',r.id);history.replaceState(null,'',u);$('results').innerHTML=''}
function setModeButtons(){['Individual','Spider','Lists'].forEach(x=>$('mode'+x).classList.toggle('active',mode===x.toLowerCase()));$('individualPanel').classList.toggle('hidden',mode!=='individual');$('spiderPanel').classList.toggle('hidden',mode!=='spider');$('listsPanel').classList.toggle('hidden',mode!=='lists')}
function buildDestinationGroups(){const m=new Map();data.forEach(r=>{const key=r.cct_destino||r.nombre_destino;if(!m.has(key))m.set(key,{key,cct:r.cct_destino,nombre:r.nombre_destino,lat:r.lat_destino,lon:r.lon_destino,alcaldia:r.alcaldia_destino,students:[]});m.get(key).students.push(r)});destinationGroups=[...m.values()].sort((a,b)=>b.students.length-a.students.length||a.nombre.localeCompare(b.nombre,'es'));$('destinationSelect').innerHTML=destinationGroups.map((g,idx)=>`<option value='${idx}'>${esc(g.nombre)} · ${esc(g.cct)} (${g.students.length})</option>`).join('')}
function renderSpider(idx){mode='spider';setModeButtons();clear();const g=destinationGroups[idx];if(!g)return;const dest=L.latLng(g.lat,g.lon),all=[];layers.spider=[];layers.dest=L.marker(dest,{icon:spiderIcon('dest',g.students.length)}).bindPopup(`<b>${esc(g.nombre)}</b><br>CCT: ${esc(g.cct)}<br>Solicitudes: ${g.students.length}<br>Alcaldía: ${esc(g.alcaldia||'No disponible')}`).addTo(map);all.push(layers.dest);let distances=[];g.students.forEach((r,n)=>{const p=L.latLng(r.lat_procedencia,r.lon_procedencia),km=distanceOf(r);distances.push(km);const color=km>3?'#c63636':km>2?'#d59b00':'#198754';const line=L.polyline([p,dest],{color,weight:2.5,opacity:.75}).bindPopup(`<b>Alumno / solicitud ID ${r.id}</b><br>${esc(r.nombre_procedencia)} → ${esc(g.nombre)}<br>Distancia: ${fmt(km)}`).addTo(map);const marker=L.marker(p,{icon:spiderIcon('origin',n+1)}).bindPopup(`<b>Alumno / solicitud ID ${r.id}</b><br>Procedencia: ${esc(r.nombre_procedencia)}<br>CCT: ${esc(r.cct_procedencia)}<br>Distancia al destino: ${fmt(km)}`).addTo(map);layers.spider.push(line,marker);all.push(marker)});map.fitBounds(L.featureGroup(all).getBounds().pad(.12));const over2=distances.filter(x=>x>2).length,over3=distances.filter(x=>x>3).length,avg=distances.reduce((a,b)=>a+b,0)/distances.length;$('spiderSummary').innerHTML=`<b>${g.students.length} solicitudes</b> hacia esta escuela.<br>Promedio: <b>${fmt(avg)}</b> · Rebasan 2 km: <b>${over2}</b> · Rebasan 3 km: <b>${over3}</b><div class='spider-legend-note'>Verde ≤2 km · Amarillo >2–3 km · Rojo >3 km</div>`;$('spiderStudents').innerHTML=g.students.slice().sort((a,b)=>distanceOf(b)-distanceOf(a)).map(r=>`<div class='student-item' data-id='${r.id}'><b>ID ${r.id} · ${esc(r.nombre_procedencia)}</b><small>${esc(r.cct_procedencia)} → ${esc(g.cct)} · ${fmt(distanceOf(r))}</small></div>`).join('')}
function buildLists(){
 const byId=new Map(data.map(r=>[String(r.id),r]));
 const normalize=x=>({
   id:String(x.id??''),
   cctProced:x.CCT_PROCED||'', nombreProced:x.nombre_procedencia||'',
   cctDestino:x.cct_primera_opcion||'', nombreDestino:x.nombre_primera_opcion||'',
   km:Number(x.Distancia_km)||0,
   linked:byId.get(String(x.id??''))
 });
 const list2=over2Data.map(normalize).sort((a,b)=>b.km-a.km);
 const list3=over3Data.map(normalize).sort((a,b)=>b.km-a.km);
 $('over2Summary').innerHTML=`<b>${list2.length}</b> estudiantes tienen su primera opción a más de 2 km.`;
 $('over3Summary').innerHTML=`<b>${list3.length}</b> estudiantes tienen su primera opción a más de 3 km.`;
 const row=x=>`<tr data-id='${esc(x.id)}' class='${x.linked?'clickable':''}' title='${x.linked?'Abrir solicitud en el mapa':'Solicitud no localizada en el visor'}'><td><b>${esc(x.id)}</b></td><td><b>${esc(x.nombreProced)}</b><small>${esc(x.cctProced)}</small></td><td><b>${esc(x.nombreDestino)}</b><small>${esc(x.cctDestino)}</small></td><td class='km-cell'>${fmt(x.km)}</td></tr>`;
 $('over2Table').innerHTML=list2.map(row).join('');
 $('over3Table').innerHTML=list3.map(row).join('');
}
function showLists(){mode='lists';setModeButtons();clear();map.setView([19.4326,-99.1332],11)}
$('modeIndividual').onclick=()=>render(i);$('modeSpider').onclick=()=>renderSpider(+$('destinationSelect').value||0);$('modeLists').onclick=showLists;$('destinationSelect').onchange=e=>renderSpider(+e.target.value);$('spiderStudents').onclick=e=>{let x=e.target.closest('[data-id]');if(x)render(data.findIndex(r=>String(r.id)===x.dataset.id))};['over2Table','over3Table'].forEach(id=>$(id).onclick=e=>{let x=e.target.closest('[data-id]');if(x){let n=data.findIndex(r=>String(r.id)===x.dataset.id);if(n>=0)render(n)}});
$('q').oninput=e=>{let q=e.target.value.toLowerCase().trim();$('results').innerHTML=q?data.filter(r=>[r.id,r.cct_procedencia,r.cct_destino,r.nombre_procedencia,r.nombre_destino].some(v=>String(v).toLowerCase().includes(q))).slice(0,20).map(r=>`<div class='hit' data-id='${r.id}'><b>ID ${r.id} · ${esc(r.cct_procedencia)} → ${esc(r.cct_destino)}</b><small>${esc(r.nombre_procedencia)} → ${esc(r.nombre_destino)}</small></div>`).join(''):''};$('results').onclick=e=>{let h=e.target.closest('.hit');if(h)render(data.findIndex(r=>String(r.id)===h.dataset.id))};$('prev').onclick=()=>render(i-1);$('next').onclick=()=>render(i+1);$('menu').onclick=()=>{$('side').classList.toggle('hide');setTimeout(()=>map.invalidateSize(),260)};$('full').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();$('buffers').onchange=e=>{showB=e.target.checked;if(mode==='individual')['b2','b3'].forEach(k=>showB?layers[k].addTo(map):map.removeLayer(layers[k]))};$('line').onchange=e=>{showL=e.target.checked;if(mode==='individual')['line','lab'].forEach(k=>showL?layers[k].addTo(map):map.removeLayer(layers[k]))};$('base').onchange=e=>{map.removeLayer(current);current=bases[e.target.value].addTo(map);current.bringToBack()};$('home').onclick=()=>render(0);$('center').onclick=()=>{const vals=Object.values(layers).flat().filter(x=>x&&x.getBounds||x&&x.getLatLng);if(vals.length)map.fitBounds(L.featureGroup(vals).getBounds().pad(.08))};map.on('mousemove',e=>$('coords').textContent=`Lat: ${e.latlng.lat.toFixed(6)} · Lon: ${e.latlng.lng.toFixed(6)}`);
Promise.all([fetch('datos/solicitudes.json').then(r=>r.json()),fetch('datos/estudiantes_mayores_2km.json').then(r=>r.json()),fetch('datos/estudiantes_mayores_3km.json').then(r=>r.json())]).then(([x,l2,l3])=>{data=x;over2Data=l2;over3Data=l3;buildDestinationGroups();buildLists();let id=new URLSearchParams(location.search).get('id'),n=id?data.findIndex(r=>String(r.id)===id):0;if(n<0){$('warn').style.display='block';$('warn').textContent='No se encontró el alumno solicitado.';n=0}render(n)}).catch(e=>{$('warn').style.display='block';$('warn').textContent='No se pudieron cargar los datos.';console.error(e)})})();
